version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "friday"
    assignees:
      - "axeleroy"
    labels:
      - "dependencies"
      - "docker"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "friday"
    assignees:
      - "axeleroy"
    labels:
        - "dependencies"
        - "github_actions"
  - package-ecosystem: "pip"
    directory: "/flask"
    schedule:
      interval: "monthly"
      day: "friday"
    assignees:
      - "axeleroy"
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/angular"
    schedule:
      interval: "monthly"
      day: "friday"
    assignees:
      - "axeleroy"
    labels:
      - "dependencies"
      - "angular"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "@angular*"
        update-types:  ["version-update:semver-major"]
      - dependency-name: "rxjs"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "typescript"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      - dependency-name: "bootstrap"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "@ng-bootstrap/ng-bootstrap"
        update-types: [ "version-update:semver-major" ]
