name: Docker publish development versions

on:
  workflow_run:
    workflows: [ "Tests" ]
    types: [ completed ]
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: haya14busa/action-workflow_run-status@v1
      -
        name: Add SHORT_SHA env property with commit short sha
        id: vars
        run: |
          calculatedSha=$(echo ${{ github.sha }} | cut -c1-7)
          echo "::set-output name=short_sha::$calculatedSha"
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: axeleroy/self-host-planning-poker:development,axeleroy/self-host-planning-poker:${{ steps.vars.outputs.short_sha }}
          # See https://docs.docker.com/build/ci/github-actions/examples/#github-cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
